name: Artifact Polling Workflow

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Task in Job 1
        run: |
          echo "Job 1 is running..."
          sleep 5
          echo "Job 1 completed."

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: job1-artifact
          path: ./artifact.txt

      - name: Create Artifact File
        run: echo "This is job1's artifact" > artifact.txt

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Poll for Artifact Availability
        run: |
          echo "Polling for job1-artifact..."
          ATTEMPTS=10
          for i in $(seq 1 $ATTEMPTS); do
            echo "Attempt $i..."
            if gh api "/repos/${{ github.repository }}/actions/artifacts" | grep -q 'job1-artifact'; then
              echo "Artifact found!"
              break
            else
              echo "Artifact not found, retrying in 5 seconds..."
              sleep 5
            fi
          done

      - name: Continue After Artifact Detection
        run: echo "Job 2 continues after artifact is available."
